name: 'Deploy Website to Github Pages'
description: "Deploys website to Github Pages container."
inputs:
  minify-src:
    description: 'JS, CSS file minification'
    required: true
    default: 'true'
  minify-res-ref:
    description: 'Minifies all resource refs in html, css, and js files. This includes the refactoring of html class, html id, and jsmacro refs.'
    required: true
    default: 'true'
  strip-jsmacros:
    description: 'Strips jsmacros from js files, and removes intermediate macro lib.'
    required: true
    default: 'true'
  generate-artifacts:
    description: 'Generates build artifacts that contain metadata from the deploy action.'
    required: true
    default: 'false'
runs:
  using: 'node12'
  main: 'dist/index.js'