name: Test builds Local Action [real]

on:
  repository_dispatch:
    types: ['build-action']
  workflow_dispatch:
    inputs:
      action-name:
        description: 'Github Action Name'
        required: true
        default: 'gh-web-deploy'
      source-ref:
        description: 'Github Action Source Branch'
        required: false
        default: 'main'
      artifact-ref:
        description: 'Github Action Artifact Branch'
        required: false
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: prepare-environment
        run: |
          ACTION_NAME="${{github.event.inputs.action-name}}"
            echo "ACTION_NAME=${ACTION_NAME}" >> $GITHUB_ENV
          BUILD_SOURCE="${{github.event.inputs.source-ref}}"
            echo "BUILD_SOURCE=${BUILD_SOURCE}" >> $GITHUB_ENV
          BUILD_TARGET="${{github.event.inputs.artifact-ref}}"       
            echo "BUILD_TARGET=${BUILD_TARGET}" >> $GITHUB_ENV
          
          git checkout "$BUILD_SOURCE"
          chmod +x "$GITHUB_WORKSPACE/.github/scripts/test.sh"
        
      - name: resolve-package
        run: |
          PACKAGE_DIR="$GITHUB_WORKSPACE/$TARGET_ACTIONS_DIR/$ACTION_NAME"
          echo "PACKAGE_DIR=${PACKAGE_DIR}" >> $GITHUB_ENV
          if [ -d "${PACKAGE_DIR}" ]; then
            echo "Resolved package '$ACTION_NAME' at $PACKAGE_DIR/"
          else
            echo "::error::Failed to find package '$ACTION_NAME' in $TARGET_ACTIONS_DIR/"
            exit 1
          fi

      - uses: actions/setup-node@v1
      - name: compile-package
        working-directory: ${{env.PACKAGE_DIR}}/
        run: |
          npm ci
          npm run build
      
      - name: prepare-artifact
        run: |
          ARTIFACT_DIR="$GITHUB_WORKSPACE/$ACTION_NAME"
            echo "ARTIFACT_DIR=${ARTIFACT_DIR}" >> $GITHUB_ENV
          ARTIFACT_SHA="$GITHUB_SHA"
            echo "ARTIFACT_SHA=${ARTIFACT_SHA}" >> $GITHUB_ENV
          ARTIFACT_SHA_SHORT="${GITHUB_SHA:0:7}"
            echo "ARTIFACT_SHA_SHORT=${ARTIFACT_SHA_SHORT}" >> $GITHUB_ENV
          ARTIFACT_AUTHOR_USER="$GITHUB_ACTOR"
            echo "ARTIFACT_AUTHOR_USER=${ARTIFACT_AUTHOR_USER}" >> $GITHUB_ENV
          ARTIFACT_AUTHOR_EMAIL="${GITHUB_ACTOR}@users.noreply.github.com"
            echo "ARTIFACT_AUTHOR_EMAIL='${ARTIFACT_AUTHOR_EMAIL}" >> $GITHUB_ENV
          
          echo "::group::Artifact Information"
          echo "artifact-name:          $ACTION_NAME"
          echo "artifact-type:          $ARTIFACT_TYPE"
          echo "artifact-sha:           $ARTIFACT_SHA_SHORT (short)"
          echo "artifact-package:       $ARTIFACT_DIR"
          echo "artifact-author-user:   $ARTIFACT_AUTHOR_USER"
          echo "artifact-author-email:  $ARTIFACT_AUTHOR_EMAIL"
          echo "artifact-creation-date: $ARTIFACT_CREATION_DATE"
          echo "artifact-publisher:     $ARTIFACT_PUBLISHER_EMAIL"
          echo "::endgroup::"

          echo "Prepared artifact $ARTIFACT_SHA"

      - name: build-artifact
        run: |
          [ -d "${ACTION_NAME}" ] && rm -rf $ACTION_NAME/* || mkdir -p $ACTION_NAME
          cd $PACKAGE_DIR

          mv dist node_modules action.yml package-lock.json \
          package.json tsconfig.json $ARTIFACT_DIR
          ls "$GITHUB_WORKSPACE"
          
          "$GITHUB_WORKSPACE/.github/scripts/test.sh"

          echo "Built artifact $ARTIFACT_SHA"

      - name: checkout_out
        uses: actions/checkout@v2
        with:
          ref: ${{env.BUILD_TARGET}}
          
      - name: publish-artifact
        run: |
          git checkout -b $BUILD_TARGET
          ls "$GITHUB_WORKSPACE"
          cd "$ARTIFACT_DIR"
          git config user.name "$ARTIFACT_PUBLISHER_NAME"
          git config user.email "$ARTIFACT_PUBLISHER_EMAIL"
          git add "."
          git commit -m $'action-dist<$ARTIFACT_SHA_SHORT>\n\nCo-authored-by $ARTIFACT_AUTHOR_USER <$ARTIFACT_AUTHOR_EMAIL>'
          git push

env:
  TARGET_ACTIONS_DIR: '.github/actions'
  ARTIFACT_TYPE: 'action-dist'

  ARTIFACT_PUBLISHER_NAME:  'github-actions'
  ARTIFACT_PUBLISHER_EMAIL: '41898282+github-actions[bot]@users.noreply.github.com'
  
