name: Test action

on:
  workflow_dispatch:
    inputs: {}
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub context
        run: echo "ARTIFACT_CREATION_DATE=`echo $(date +'%Y-%m-%dT%H:%M:%SZ')`" >> $GITHUB_ENV
      - run: |
          yes="set${GITHUB_ENV:3}"
          echo $yes

env:
  ARTIFACT_METADATA_SCHEMA_PLACEHOLDER: >
    "artifact-name":"$name",
    "artifact-sha":"$sha",
    "artifact-package":"$package",
    "artifact-author-user":"$author-user",
    "artifact-author-email":"$author-email",
    "artifact-creation-date":"$date"
