name: Builds Local Action

on:
  workflow_dispatch:
    inputs:
      action-name:
        description: 'Github Action Name'
        required: true
        default: 'gh-delpoy'
      artifact-ref:
        description: 'Github Action Source Branch'
        required: false
        default: 'main'
      artifact-out:
        description: 'Github Action Artifact Branch'
        required: false
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: prepare-environment
        run: |
          echo "$INPUT_ACTION-NAME"
          echo "${{env.INPUT_ACTION-NAME}}"
          echo "${{github.event.inputs.action-name}}"
          echo "${{inputs.action-name}}"
          echo "ACTION_NAME='${INPUT_ACTION-NAME}'" >> $GITHUB_ENV
          echo "BUILD_SOURCE='${INPUT_ARTIFACT-REF}'" >> $GITHUB_ENV
          echo "BUILD_TARGET='${INPUT_ARTIFACT-OUT}" >> $GITHUB_ENV
